### ISSUE TITLE
Feature request: Option to require re-acknowledge of alarms after set amount of time

### ISSUE THREAD

**Issue by deltaford** [arbox0/NightWidget#1]
When for example an upper warning is triggered and acknowledged, no more alarms are triggered even if value continues to be high for hours (unless upper alarm is exceeded). It would be nice (specially during night) if warnings/alarms could be triggered again If value continue to exceed threshold for a set duration of xx min or xx hours.

**Comment by deltaford** [comment]
It seems this was added in v2.0 RC2 :-)

**Comment by arbox0** [comment]
There was a lot of bugs V2.0 RC2 I have had to refactor the code... try this version better ;-)  https://github.com/arbox0/NightWidget/releases/tag/NIGHTWIDGET2_R2

**Comment by deltaford** [comment]
Will do. Thanks! :-)
