### ISSUE TITLE
dot/period (.) not allowed in threshold values?

### ISSUE THREAD

**Issue by anderfo** [arbox0/NightWidget#2]
When I'm entering the threshold values, they are originally written with period (e.g. 7.4). But if I by accident delete the dot/period, I'm unable to punch in a new one from the keyboard — only numbers are permitted... I've also tried copying a period mark from the browser on my phone, but I'm unable to paste it in the widget setting.

**Comment by arbox0** [comment]
Please, test this version https://github.com/arbox0/NightWidget/releases/tag/NIGHTWIDGET2_R2_U2
and tell me if it is solved or not

**Comment by anderfo** [comment]
Great, it works now! Issue solved.
