### ISSUE TITLE
Mongo upgrade will break NightWidget

### ISSUE THREAD

**Issue by jasoncalabrese** [arbox0/NightWidget#5]
Need new mongo driver, would also be great to add support calling the Nightscout API.  If you're interested in doing that ping us over at https://gitter.im/nightscout/public
#### Info from Mongolab:

> MongoDB 3.0 is now generally available on MongoLab, so we are in the process of making it the default release version for all new MongoLab deployments. We are also taking steps to discontinue our support for MongoDB 2.4.
> 
> To this end, on Wednesday, September 30, we will upgrade all free Sandbox databases running MongoDB 2.6 to MongoDB 3.0. In addition, we will upgrade all for-pay Shared databases running MongoDB 2.4 to MongoDB 2.6.
> 
> You must ensure that your free Sandbox databases running 2.6 meet the upgrade requirements for 3.0 which includes a list of MongoDB 3.0-compatible drivers. If you do not upgrade your app to a 3.0-compatible driver before this upgrade, you may be unable to connect to your deployment.

**Comment by arbox0** [comment]
Mongo REST API Implemented on the lastest release
